# Generated by Django 4.1.7 on 2023-03-30 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'News', 'verbose_name_plural': 'News'},
        ),
        migrations.AlterField(
            model_name='news',
            name='main_image',
            field=models.ImageField(upload_to='media/photos'),
        ),
        migrations.AlterField(
            model_name='news',
            name='preview_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/photos_low'),
        ),
    ]
