# Generated by Django 4.1.7 on 2023-04-19 05:21

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 1, 1, 0, 0)),
        ),
    ]
