version: "3.9"

services:
  db:
    image: postgres:15
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      .env

  redis:
    image: redis:4.0-alpine
    hostname: redis
    env_file:
      - .env

  news:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: news_docker
    depends_on:
      - db
      - redis
    volumes:
      - .:/backend
      - ./staticfiles:/backend/static
      - .data/db:/backend/data/db
    env_file:
      - .env
    entrypoint: bash ./run_backends.sh
    ports:
      - '8000:8000'

