# Generated by Django 4.1.7 on 2023-04-04 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notable_places', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='lat',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='place',
            name='lon',
            field=models.FloatField(default=0),
        ),
    ]
